-- 1. Schema examen
CREATE TABLE HOTEL (
   ID_HOTEL INT AUTO_INCREMENT,
   DENUMIRE VARCHAR(255) NOT NULL,
   ZONA VARCHAR(255),
   JUDET VARCHAR(255),
   LOCALITATE VARCHAR(255),
   NUMAR_STELE INT,
   PRIMARY KEY (ID_HOTEL)
);

CREATE TABLE REZERVARE (
   ID_REZERVARE INT AUTO_INCREMENT,
   DATA_SOSIRE DATE NOT NULL,
   DATA_PLECARE DATE NOT NULL,
   PERSOANA_CONTACT VARCHAR(255) NOT NULL,
   TELEFON VARCHAR(20),
   PRIMARY KEY (ID_REZERVARE)
);

CREATE TABLE CAMERA (
   ID_CAMERA INT AUTO_INCREMENT,
   NUMAR INT NOT NULL,
   ETAJ INT NOT NULL,
   OBSERVATII TEXT,
   ID_HOTEL INT,
   TARIF_PE_NOAPTE DECIMAL(10, 2) NOT NULL,
   PRIMARY KEY (ID_CAMERA),
   FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL(ID_HOTEL)
);

CREATE TABLE CAZARE (
   ID_CAZARE INT AUTO_INCREMENT,
   DATA_SOSIRE DATE NOT NULL,
   DATA_PLECARE DATE NOT NULL,
   ID_REZERVARE INT,
   ID_CAMERA INT,
   PRIMARY KEY (ID_CAZARE),
   FOREIGN KEY (ID_REZERVARE) REFERENCES REZERVARE(ID_REZERVARE),
   FOREIGN KEY (ID_CAMERA) REFERENCES CAMERA(ID_CAMERA)
);

-- tabela de users
CREATE TABLE USER (
   ID_USER INT AUTO_INCREMENT,
   EMAIL VARCHAR(255) NOT NULL,
   PAROLA VARCHAR(255) NOT NULL,
   PRIMARY KEY (ID_USER),
   UNIQUE (EMAIL)
);